---
#Here you can change the messages that will display
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§5M§bL§7Staff"
#The content of the menu (Description)
Content: "§4Owners: §7RoseCrib2833078"
#Returns button name
Button: "§aOkaay!!"
...
